name: "update dist/index.js"
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: install dependencies
      run: |
        npm ci
    - name: format TypeScript code
      run: |
        npm run format
    - name: compile TypeScript code
      run: |
        npm run build
    - name: compile TypeScript code into dist/index.js
      run: |
        npm run pack
    - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
      with:
        commit_message: "chore(build): automated change"
